version: "3.9"

services:
  prometheus0:
    profiles:
      - "sidecar"
    image: prom/prometheus:v2.36.0
    container_name: prometheus0
    user: root
    volumes:
      - thanos0:/data
      - ./configs/prometheus/prometheus1.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/data/prom0"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.min-block-duration=30m"
      - "--storage.tsdb.max-block-duration=30m"
      - "--web.listen-address=0.0.0.0:9090"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    depends_on:
      - minio
    networks:
      - thanos
    restart: always

  prometheus1:
    profiles:
      - "sidecar"
    image: prom/prometheus:v2.36.0
    container_name: prometheus1
    user: root
    volumes:
      - thanos1:/data
      - ./configs/prometheus/prometheus2.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/data/prom1"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.min-block-duration=30m"
      - "--storage.tsdb.max-block-duration=30m"
      - "--web.listen-address=0.0.0.0:9091"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    depends_on:
      - minio
    networks:
      - thanos

  prometheus2:
    profiles:
      - "remote-write"
    image: prom/prometheus:v2.36.0
    container_name: prometheus2
    user: root
    volumes:
      - thanos2:/data
      - ./configs/prometheus/prometheus3.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--log.level=debug"
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/data/prom1"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.min-block-duration=30m"
      - "--storage.tsdb.max-block-duration=30m"
      - "--web.listen-address=0.0.0.0:9091"
    depends_on:
      - minio
      - thanos-receive
    networks:
      - thanos

  sidecar0:
    profiles:
      - "sidecar"
    image: thanosio/thanos:v0.26.0
    container_name: thanos-sidecar0
    command:
      - "sidecar"
      - "--debug.name=sidecar-0"
      - "--grpc-address=0.0.0.0:10901"
      - "--grpc-grace-period=1s"
      - "--http-address=0.0.0.0:10902"
      - "--http-grace-period=1s"
      - "--prometheus.url=http://prometheus0:9090"
      - "--tsdb.path=/data/prom0"
      - "--objstore.config-file=/bucket.yaml"
    volumes:
      - thanos0:/data
      - ./configs/object_store/bucket.yaml:/bucket.yaml
    depends_on:
      - minio
      - prometheus0
    networks:
      - thanos

  sidecar1:
    profiles:
      - "sidecar"
    image: thanosio/thanos:v0.26.0
    container_name: thanos-sidecar1
    command:
      - "sidecar"
      - "--debug.name=sidecar-1"
      - "--grpc-address=0.0.0.0:10911"
      - "--grpc-grace-period=1s"
      - "--http-address=0.0.0.0:10912"
      - "--http-grace-period=1s"
      - "--prometheus.url=http://prometheus1:9091"
      - "--tsdb.path=/data/prom1"
      - "--objstore.config-file=/bucket.yaml"
    volumes:
      - thanos1:/data
      - ./configs/object_store/bucket.yaml:/bucket.yaml
    depends_on:
      - minio
      - prometheus1
    networks:
      - thanos

  thanos-store:
    image: thanosio/thanos:v0.26.0
    container_name: thanos-store
    restart: always
    command:
      - "store"
      - "--debug.name=store"
      - "--grpc-address=0.0.0.0:10905"
      - "--grpc-grace-period=1s"
      - "--http-address=0.0.0.0:10906"
      - "--http-grace-period=1s"
      - "--data-dir=/data/store"
      - "--objstore.config-file=/bucket.yaml"
    volumes:
      - store:/data
      - ./configs/object_store/bucket.yaml:/bucket.yaml
    ports:
      - 10906:10906
    depends_on:
      - minio
      - mc
    networks:
      - thanos

  thanos-receive:
    image: thanos:latest
    container_name: thanos-receive
    command:
      - "receive"
      - "--log.level=debug"
      - "--debug.name=receive"
      - "--tsdb.path=/data/remote-write-receive-data"
      - "--grpc-address=0.0.0.0:10907"
      - "--http-address=0.0.0.0:10909"
      - '--label=receive="true"'
      - "--objstore.config-file=/bucket.yaml"
      - "--remote-write.address=0.0.0.0:10908"
    volumes:
      - receive:/data
      - ./configs/object_store/bucket.yaml:/bucket.yaml
    depends_on:
      - minio
    networks:
      - thanos

  query-frontend:
    image: quay.io/thanos/thanos:v0.26.0
    container_name: thanos-query-frontend
    command:
      - "query-frontend"
      - "--http-address=0.0.0.0:10901"
      - "--query-frontend.downstream-url=http://thanos-query:10904"
    ports:
      - 10901:10901
    depends_on:
      - thanos-query
    networks:
      - thanos
    restart: always

  thanos-query:
    image: thanosio/thanos:v0.26.0
    container_name: thanos-query
    command:
      - "query"
      - "--debug.name=query0"
      - "--grpc-address=0.0.0.0:10903"
      - "--grpc-grace-period=1s"
      - "--http-address=0.0.0.0:10904"
      - "--http-grace-period=1s"
      - "--query.replica-label=prometheus"
      - "--store=sidecar0:10901"
      - "--store=sidecar1:10911"
      - "--store=thanos-store:10905"
      - "--store=thanos-receive:10907"
    ports:
      - 10904:10904
    depends_on:
      - minio
      - sidecar0
      - sidecar1
      - sidecar2
      - thanos-store
      - thanos-receive
    networks:
      - thanos

  thanos-compact:
    image: thanosio/thanos:v0.26.0
    container_name: thanos-compact
    command:
      - "compact"
      - "--data-dir=/tmp/thanos-compact"
      - "--objstore.config-file=/bucket.yaml"
      - "--http-address=0.0.0.0:10902"
      - "--http-grace-period=2m"
      - "--consistency-delay=30m"
      - "--wait"
    volumes:
      - compact:/tmp
      - ./configs/object_store/bucket.yaml:/bucket.yaml
    depends_on:
      - minio
      - mc
      - thanos-store
      - sidecar0
      - sidecar1
    networks:
      - thanos

  grafana:
    image: grafana/grafana:6.5.2
    container_name: grafana
    #volumes:
    #  - grafana_data:/var/lib/grafana
    #  - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - thanos

  node-exporter:
    image: prom/node-exporter:v0.18.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
    networks:
      - thanos

  minio:
    image: minio/minio:RELEASE.2022-05-08T23-50-31Z.hotfix.a8c39d7cb
    container_name: minio
    hostname: minio
    volumes:
      - minio:/export
    ports:
      - "9000:9000"
    networks:
      - thanos
    environment:
      MINIO_ACCESS_KEY: EXAMPLEKEY
      MINIO_SECRET_KEY: EXAMPLESECRET
    command: server /export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mc:
    image: minio/mc
    container_name: mc
    entrypoint: |
      sh -c 'sh -s << EOF
      mc alias set myminio http://minio:9000 EXAMPLEKEY EXAMPLESECRET
      mc mb myminio/thanos
      mc policy set public myminio/thanos
      exit 0
      EOF'
    networks:
      - thanos
    depends_on:
      - minio

  avalanche:
    image: quay.io/observatorium/avalanche:make-tenant-header-configurable-2021-10-07-0a2cbf5
    container_name: avalanche
    networks:
      - thanos
    command:
      - --remote-url=http://thanos-receive:10908/api/v1/receive
      - --metric-count=1
      - --series-count=10000
      - --remote-write-interval=15s
      - --remote-requests-count=1000000
      - --value-interval=3600
      - --series-interval=315360000
      - --metric-interval=315360000
      - --remote-tenant-header=THANOS-TENANT
      - --remote-tenant=0fc2b00e-201b-4c17-b9f2-19d91adc4fd2

networks:
  thanos: {}

volumes:
  minio: {}
  thanos0: {}
  thanos1: {}
  thanos2: {}
  store: {}
  receive: {}
  compact: {}
