global:
  external_labels:
    prometheus: prom-1
scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
      - targets:
          - "localhost:9091"
  - job_name: thanos-sidecar
    scrape_interval: 15s
    static_configs:
      - targets:
          - "sidecar1:10912"
  - job_name: thanos-store
    scrape_interval: 15s
    static_configs:
      - targets:
          - "thanos-store:10906"
  - job_name: thanos-receive
    scrape_interval: 15s
    static_configs:
      - targets:
          - "thanos-receive:10909"
  - job_name: thanos-query
    scrape_interval: 15s
    static_configs:
      - targets:
          - "thanos-query:10904"
