global:
  external_labels:
    prometheus: prom-0
scrape_configs:
  # When the Thanos remote-write-receive component is started,
  # this is an example configuration of a Prometheus server that
  # would scrape a local node-exporter and replicate its data to
  # the remote write endpoint.
  - job_name: node
    scrape_interval: 15s
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
      - targets:
          - "localhost:9091"
  - job_name: thanos-sidecar
    scrape_interval: 15s
    static_configs:
      - targets:
          - "sidecar0:10902"
  - job_name: thanos-store
    scrape_interval: 15s
    static_configs:
      - targets:
          - "thanos-store:10906"
  - job_name: thanos-receive
    scrape_interval: 15s
    static_configs:
      - targets:
          - "thanos-receive:10909"
  - job_name: thanos-query
    scrape_interval: 15s
    static_configs:
      - targets:
          - "thanos-query:10904"
