version: "3.9"

services:
  thanos-store:
    image: thanosio/thanos:v0.26.0
    container_name: thanos-store
    restart: always
    command:
      - "store"
      - "--debug.name=store"
      - "--grpc-address=0.0.0.0:10905"
      - "--grpc-grace-period=1s"
      - "--http-address=0.0.0.0:10906"
      - "--http-grace-period=1s"
      - "--data-dir=/data/store"
      - "--objstore.config-file=/bucket.yaml"
    volumes:
      - store:/data
      - ./object_store/bucket.yaml:/bucket.yaml
    ports:
      - 10906:10906
    depends_on:
      - minio
      - mc
    networks:
      - thanos

  query-frontend:
    image: quay.io/thanos/thanos:v0.26.0
    container_name: thanos-query-frontend
    command:
      - "query-frontend"
      - "--http-address=0.0.0.0:10901"
      - "--query-frontend.downstream-url=http://thanos-query:10904"
    ports:
      - 10901:10901
    depends_on:
      - thanos-query
    networks:
      - thanos
    restart: always

  thanos-compact:
    image: thanosio/thanos:v0.26.0
    container_name: thanos-compact
    command:
      - "compact"
      - "--data-dir=/tmp/thanos-compact"
      - "--objstore.config-file=/bucket.yaml"
      - "--http-address=0.0.0.0:10902"
      - "--http-grace-period=2m"
      - "--consistency-delay=30m"
      - "--wait"
    volumes:
      - compact:/tmp
      - ./object_store/bucket.yaml:/bucket.yaml
    depends_on:
      - minio
      - mc
      - thanos-store
    networks:
      - thanos

  node-exporter:
    image: prom/node-exporter:v0.18.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
    networks:
      - thanos

  minio:
    image: minio/minio:RELEASE.2022-07-30T05-21-40Z
    container_name: minio
    hostname: minio
    volumes:
      - minio:/export
    ports:
      - "9000:9000"
      - "8000:8000"
    networks:
      - thanos
    environment:
      MINIO_ACCESS_KEY: EXAMPLEKEY
      MINIO_SECRET_KEY: EXAMPLESECRET
    command: server /export --console-address :8000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/console" ]
      interval: 30s
      timeout: 20s
      retries: 3

  mc:
    image: minio/mc
    container_name: mc
    entrypoint: |
      sh -c 'sh -s << EOF
      mc alias set myminio http://minio:9000 EXAMPLEKEY EXAMPLESECRET
      mc mb myminio/thanos
      mc policy set public myminio/thanos
      exit 0
      EOF'
    networks:
      - thanos
    depends_on:
      - minio

networks:
  thanos: {}

volumes:
  minio: {}
  thanos0: {}
  thanos1: {}
  store: {}
  receive: {}
  compact: {}
