version: "3.9"

services:
  prometheus-remote-write:
    image: prom/prometheus:v2.36.0
    container_name: prometheus_remote_write
    user: root
    volumes:
      - prometheus_remote_write:/data
      - ./prometheus/remote_write.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--log.level=debug"
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/data/prom1"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.min-block-duration=30m"
      - "--storage.tsdb.max-block-duration=30m"
      - "--web.listen-address=0.0.0.0:9091"
    depends_on:
      - minio
      - thanos-receive
    networks:
      - thanos

  thanos-receive:
    image: thanosio/thanos:v0.28.1
    container_name: thanos-receive
    command:
      - "receive"
      - "--log.level=debug"
      - "--debug.name=receive"
      - "--tsdb.path=/data/remote-write-receive-data"
      - "--grpc-address=0.0.0.0:10907"
      - "--http-address=0.0.0.0:10909"
      - '--label=receive="true"'
      - "--objstore.config-file=/bucket.yaml"
      - "--remote-write.address=0.0.0.0:10908"
    volumes:
      - receive:/data
      - ./object_store/bucket.yaml:/bucket.yaml
    depends_on:
      - minio
    networks:
      - thanos

  avalanche:
    image: quay.io/observatorium/avalanche:make-tenant-header-configurable-2021-10-07-0a2cbf5
    container_name: avalanche
    networks:
      - thanos
    command:
      - --remote-url=http://thanos-receive:10908/api/v1/receive
      - --metric-count=1
      - --series-count=10000
      - --remote-write-interval=15s
      - --remote-requests-count=1000000
      - --value-interval=3600
      - --series-interval=315360000
      - --metric-interval=315360000
      - --remote-tenant-header=THANOS-TENANT
      - --remote-tenant=0fc2b00e-201b-4c17-b9f2-19d91adc4fd2

  thanos-query:
    image: thanosio/thanos:v0.28.1
    container_name: thanos-query
    command:
      - "query"
      - "--debug.name=query0"
      - "--grpc-address=0.0.0.0:10903"
      - "--grpc-grace-period=1s"
      - "--http-address=0.0.0.0:10904"
      - "--http-grace-period=1s"
      - "--query.replica-label=prometheus"
      - "--store=sidecar0:10901"
      - "--store=sidecar1:10911"
      - "--store=thanos-store:10905"
      - "--store=thanos-receive:10907"
    ports:
      - 10904:10904
    depends_on:
      - minio
      - thanos-store
      - thanos-receive
    networks:
      - thanos

volumes:
  prometheus_remote_write: {}
